"use client";

import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { trackMetaEvent } from "@/lib/metaPixel";

export default function UrgencyBanner() {
  const [activeCode, setActiveCode] = useState<string | null>(null);
  const [timeLeft, setTimeLeft] = useState<{ d: number; h: number; m: number; s: number } | null>(null);

  const checkCode = () => {
    const code = localStorage.getItem("mw_discount_code");
    const expiresStr = localStorage.getItem("mw_discount_expires");
    
    if (code && expiresStr) {
      const expiresAt = parseInt(expiresStr);
      const now = Date.now();
      
      if (expiresAt > now) {
        setActiveCode(code);
        calculateTimeLeft(expiresAt);
      } else {
        // Expired
        trackMetaEvent('ExpiredDiscount', { code_lost: code }, true);

        const level = localStorage.getItem("mw_discount_level");
        
        if (level === "10") {
          localStorage.setItem("mw_discount_expired_once", "true");
        } else if (level === "5") {
          localStorage.setItem("mw_discount_blacklisted", "true");
        }

        localStorage.removeItem("mw_discount_code");
        localStorage.removeItem("mw_discount_expires");
        localStorage.removeItem("mw_discount_level");
        
        setActiveCode(null);
        setTimeLeft(null);
      }
    }
  };

  useEffect(() => {
    checkCode();

    // Listen for new codes generated by the scratch card
    window.addEventListener('mw_code_generated', checkCode);
    
    // Update countdown every second if there's an active code
    const interval = setInterval(() => {
      checkCode();
    }, 1000);

    return () => {
      window.removeEventListener('mw_code_generated', checkCode);
      clearInterval(interval);
    };
  }, []);

  const calculateTimeLeft = (expiresAt: number) => {
    const difference = expiresAt - Date.now();
    
    if (difference > 0) {
      setTimeLeft({
        d: Math.floor(difference / (1000 * 60 * 60 * 24)),
        h: Math.floor((difference / (1000 * 60 * 60)) % 24),
        m: Math.floor((difference / 1000 / 60) % 60),
        s: Math.floor((difference / 1000) % 60)
      });
    }
  };

  if (!activeCode || !timeLeft) return null;

  return (
    <AnimatePresence>
      <motion.div 
        initial={{ y: 50, opacity: 0, x: "-50%" }}
        animate={{ y: 0, opacity: 1, x: "-50%" }}
        className="fixed bottom-8 left-1/2 z-[100] flex flex-col md:flex-row items-center justify-center gap-2 md:gap-4 bg-matte-black/95 backdrop-blur-md text-white py-3 px-6 rounded-full shadow-[0_-10px_40px_rgba(0,0,0,0.8)] border border-metallic-gold/40 whitespace-nowrap"
      >
        <span className="text-[10px] md:text-xs font-light uppercase tracking-widest text-center text-gray-300">
          Code <span className="text-metallic-gold font-bold mx-1 tracking-widest">{activeCode}</span> Activated
        </span>
        <span className="hidden md:inline text-white/20 font-light">|</span>
        <span className="text-[10px] md:text-xs font-medium tracking-widest flex items-center gap-2 text-gray-300">
          Time left to freeze code: 
          <span className="font-mono font-bold text-metallic-gold">
            {timeLeft.d > 0 && `${timeLeft.d}d `}
            {timeLeft.h.toString().padStart(2, '0')}h {timeLeft.m.toString().padStart(2, '0')}m {timeLeft.s.toString().padStart(2, '0')}s
          </span>
        </span>
        
        <a 
          href={`https://wa.me/17542673047?text=Hi!%20I%20want%20to%20freeze%20my%20Golden%20Ticket%20discount%20code:%20${activeCode}`}
          target="_blank"
          rel="noopener noreferrer"
          className="ml-2 bg-[#25D366] text-white px-3 py-1 rounded-sm text-[9px] md:text-[10px] font-bold uppercase tracking-widest hover:bg-[#128C7E] transition-colors"
        >
          Freeze Now
        </a>
      </motion.div>
    </AnimatePresence>
  );
}
